//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCommandHandlers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicCommandHandlers.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to listen to : .
        /// </summary>
        internal static string ActionToListenTo {
            get {
                return ResourceManager.GetString("ActionToListenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate a mode.
        /// </summary>
        internal static string AddMode {
            get {
                return ResourceManager.GetString("AddMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-Left.
        /// </summary>
        internal static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-Right.
        /// </summary>
        internal static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click type : .
        /// </summary>
        internal static string ClickProtocolSubtitle {
            get {
                return ResourceManager.GetString("ClickProtocolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables simulating a mouse clic (left, right double etc...).
        /// </summary>
        internal static string ClicProtocolDescription {
            get {
                return ResourceManager.GetString("ClicProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse clicks.
        /// </summary>
        internal static string ClicProtocolTitle {
            get {
                return ResourceManager.GetString("ClicProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit CiviKey?.
        /// </summary>
        internal static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double left click.
        /// </summary>
        internal static string DoubleLeftClick {
            get {
                return ResourceManager.GetString("DoubleLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close CiviKey.
        /// </summary>
        internal static string DynCommandClose {
            get {
                return ResourceManager.GetString("DynCommandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide CiviKey&apos;s configuration panel.
        /// </summary>
        internal static string DynCommandHide {
            get {
                return ResourceManager.GetString("DynCommandHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the keyboard.
        /// </summary>
        internal static string DynCommandMinimize {
            get {
                return ResourceManager.GetString("DynCommandMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables triggering other actions (close CiviKey, minimize the keyboard...).
        /// </summary>
        internal static string DynCommandProtocolDescription {
            get {
                return ResourceManager.GetString("DynCommandProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string DynCommandProtocolTitle {
            get {
                return ResourceManager.GetString("DynCommandProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push the &apos;Windows&apos; key.
        /// </summary>
        internal static string DynCommandWindowsKey {
            get {
                return ResourceManager.GetString("DynCommandWindowsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file from your computer.
        /// </summary>
        internal static string FileLauncherBrowse {
            get {
                return ResourceManager.GetString("FileLauncherBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file or launch an application from your computer.
        /// </summary>
        internal static string FileLauncherDescription {
            get {
                return ResourceManager.GetString("FileLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An installed application.
        /// </summary>
        internal static string FileLauncherInstalledApps {
            get {
                return ResourceManager.GetString("FileLauncherInstalledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        internal static string FileLauncherTitle {
            get {
                return ResourceManager.GetString("FileLauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a name to this action :.
        /// </summary>
        internal static string GiveName {
            get {
                return ResourceManager.GetString("GiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables showing the keyboard&apos;s help panel.
        /// </summary>
        internal static string HelpProtocolDescription {
            get {
                return ResourceManager.GetString("HelpProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpProtocolTitle {
            get {
                return ResourceManager.GetString("HelpProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        internal static string IsRecordingText {
            get {
                return ResourceManager.GetString("IsRecordingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard : .
        /// </summary>
        internal static string KeyboardProtocolSubtitle {
            get {
                return ResourceManager.GetString("KeyboardProtocolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &quot;classic&quot; key has been pressed (a, z, b, t etc...).
        /// </summary>
        internal static string KeySent {
            get {
                return ResourceManager.GetString("KeySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the sequence : .
        /// </summary>
        internal static string KeySequenceNameTitle {
            get {
                return ResourceManager.GetString("KeySequenceNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables recording a key combination.
        /// </summary>
        internal static string KeySequenceProtocolDescription {
            get {
                return ResourceManager.GetString("KeySequenceProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key sequences.
        /// </summary>
        internal static string KeySequenceProtocolTitle {
            get {
                return ResourceManager.GetString("KeySequenceProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click.
        /// </summary>
        internal static string LeftClick {
            get {
                return ResourceManager.GetString("LeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action : .
        /// </summary>
        internal static string ModeProtocolActionsSubtitle {
            get {
                return ResourceManager.GetString("ModeProtocolActionsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables interacting with modes : removing, adding or setting one.
        /// </summary>
        internal static string ModeProtocolDescription {
            get {
                return ResourceManager.GetString("ModeProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied to : .
        /// </summary>
        internal static string ModeProtocolModesSubtitle {
            get {
                return ResourceManager.GetString("ModeProtocolModesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes (ctrl, shift, alt...).
        /// </summary>
        internal static string ModeProtocolTitle {
            get {
                return ResourceManager.GetString("ModeProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the command sent when the action above is triggered.
        /// </summary>
        internal static string MonitorOnceInnerActionTitle {
            get {
                return ResourceManager.GetString("MonitorOnceInnerActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables triggering an action right after another (change the mode after the next click on a key).
        /// </summary>
        internal static string MonitorOnceProtocolDescription {
            get {
                return ResourceManager.GetString("MonitorOnceProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain actions.
        /// </summary>
        internal static string MonitorOnceProtocolTitle {
            get {
                return ResourceManager.GetString("MonitorOnceProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts moving the mouse pointer towards a direction, clicking again the key will stop the motion.
        /// </summary>
        internal static string MoveMouseProtocolDescription {
            get {
                return ResourceManager.GetString("MoveMouseProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the mouse pointer.
        /// </summary>
        internal static string MoveMouseProtocolTitle {
            get {
                return ResourceManager.GetString("MoveMouseProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push the left button.
        /// </summary>
        internal static string PushLeft {
            get {
                return ResourceManager.GetString("PushLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release the left button.
        /// </summary>
        internal static string ReleaseLeft {
            get {
                return ResourceManager.GetString("ReleaseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivate a mode.
        /// </summary>
        internal static string RemoveMode {
            get {
                return ResourceManager.GetString("RemoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click.
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables sending a special key : Return, F1 to F12, Suppr etc....
        /// </summary>
        internal static string SendKeyProtocolDescription {
            get {
                return ResourceManager.GetString("SendKeyProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action : .
        /// </summary>
        internal static string SendKeyProtocolSubtitle {
            get {
                return ResourceManager.GetString("SendKeyProtocolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Key (F11, Return, Suppr ...).
        /// </summary>
        internal static string SendKeyProtocolTitle {
            get {
                return ResourceManager.GetString("SendKeyProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a mode as the current (and only) one.
        /// </summary>
        internal static string SetMode {
            get {
                return ResourceManager.GetString("SetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the keyboard&apos;s help panel.
        /// </summary>
        internal static string ShowHelpAction {
            get {
                return ResourceManager.GetString("ShowHelpAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        internal static string StartRecordingTitle {
            get {
                return ResourceManager.GetString("StartRecordingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        internal static string StopRecordingTitle {
            get {
                return ResourceManager.GetString("StopRecordingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a placeholder.
        /// </summary>
        internal static string TextTemplateAdd {
            get {
                return ResourceManager.GetString("TextTemplateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a template.
        /// </summary>
        internal static string TextTemplateDescription {
            get {
                return ResourceManager.GetString("TextTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a template.
        /// </summary>
        internal static string TextTemplateTitle {
            get {
                return ResourceManager.GetString("TextTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle a mode.
        /// </summary>
        internal static string ToggleMode {
            get {
                return ResourceManager.GetString("ToggleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-Left.
        /// </summary>
        internal static string UpLeft {
            get {
                return ResourceManager.GetString("UpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-Right.
        /// </summary>
        internal static string UpRight {
            get {
                return ResourceManager.GetString("UpRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
