//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicCommandHandlers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicCommandHandlers.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action to listen to : .
        /// </summary>
        public static string ActionToListenTo {
            get {
                return ResourceManager.GetString("ActionToListenTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate a mode.
        /// </summary>
        public static string AddMode {
            get {
                return ResourceManager.GetString("AddMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-Left.
        /// </summary>
        public static string BottomLeft {
            get {
                return ResourceManager.GetString("BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-Right.
        /// </summary>
        public static string BottomRight {
            get {
                return ResourceManager.GetString("BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click type : .
        /// </summary>
        public static string ClickProtocolSubtitle {
            get {
                return ResourceManager.GetString("ClickProtocolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables simulating a mouse clic (left, right double etc...).
        /// </summary>
        public static string ClicProtocolDescription {
            get {
                return ResourceManager.GetString("ClicProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse clicks.
        /// </summary>
        public static string ClicProtocolTitle {
            get {
                return ResourceManager.GetString("ClicProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double left click.
        /// </summary>
        public static string DoubleLeftClick {
            get {
                return ResourceManager.GetString("DoubleLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close CiviKey.
        /// </summary>
        public static string DynCommandClose {
            get {
                return ResourceManager.GetString("DynCommandClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide CiviKey&apos;s configuration panel.
        /// </summary>
        public static string DynCommandHide {
            get {
                return ResourceManager.GetString("DynCommandHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize the keyboard.
        /// </summary>
        public static string DynCommandMinimize {
            get {
                return ResourceManager.GetString("DynCommandMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables triggering other actions (close CiviKey, minimize the keyboard...).
        /// </summary>
        public static string DynCommandProtocolDescription {
            get {
                return ResourceManager.GetString("DynCommandProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string DynCommandProtocolTitle {
            get {
                return ResourceManager.GetString("DynCommandProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push the &apos;Windows&apos; key.
        /// </summary>
        public static string DynCommandWindowsKey {
            get {
                return ResourceManager.GetString("DynCommandWindowsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file from your computer.
        /// </summary>
        public static string FileLauncherBrowse {
            get {
                return ResourceManager.GetString("FileLauncherBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a file or launch an application from your computer.
        /// </summary>
        public static string FileLauncherDescription {
            get {
                return ResourceManager.GetString("FileLauncherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An installed application.
        /// </summary>
        public static string FileLauncherInstalledApps {
            get {
                return ResourceManager.GetString("FileLauncherInstalledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string FileLauncherTitle {
            get {
                return ResourceManager.GetString("FileLauncherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a name to this action :.
        /// </summary>
        public static string GiveName {
            get {
                return ResourceManager.GetString("GiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables showing the keyboard&apos;s help panel.
        /// </summary>
        public static string HelpProtocolDescription {
            get {
                return ResourceManager.GetString("HelpProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpProtocolTitle {
            get {
                return ResourceManager.GetString("HelpProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard : .
        /// </summary>
        public static string KeyboardProtocolSubtitle {
            get {
                return ResourceManager.GetString("KeyboardProtocolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &quot;classic&quot; key has been pressed (a, z, b, t etc...).
        /// </summary>
        public static string KeySent {
            get {
                return ResourceManager.GetString("KeySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click.
        /// </summary>
        public static string LeftClick {
            get {
                return ResourceManager.GetString("LeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action : .
        /// </summary>
        public static string ModeProtocolActionsSubtitle {
            get {
                return ResourceManager.GetString("ModeProtocolActionsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables interacting with modes : removing, adding or setting one.
        /// </summary>
        public static string ModeProtocolDescription {
            get {
                return ResourceManager.GetString("ModeProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied to : .
        /// </summary>
        public static string ModeProtocolModesSubtitle {
            get {
                return ResourceManager.GetString("ModeProtocolModesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modes (ctrl, shift, alt...).
        /// </summary>
        public static string ModeProtocolTitle {
            get {
                return ResourceManager.GetString("ModeProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the command sent when the action above is triggered.
        /// </summary>
        public static string MonitorOnceInnerActionTitle {
            get {
                return ResourceManager.GetString("MonitorOnceInnerActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables triggering an action right after another (change the mode after the next click on a key).
        /// </summary>
        public static string MonitorOnceProtocolDescription {
            get {
                return ResourceManager.GetString("MonitorOnceProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain actions.
        /// </summary>
        public static string MonitorOnceProtocolTitle {
            get {
                return ResourceManager.GetString("MonitorOnceProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts moving the mouse pointer towards a direction, clicking again the key will stop the motion.
        /// </summary>
        public static string MoveMouseProtocolDescription {
            get {
                return ResourceManager.GetString("MoveMouseProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the mouse pointer.
        /// </summary>
        public static string MoveMouseProtocolTitle {
            get {
                return ResourceManager.GetString("MoveMouseProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push the left button.
        /// </summary>
        public static string PushLeft {
            get {
                return ResourceManager.GetString("PushLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release the left button.
        /// </summary>
        public static string ReleaseLeft {
            get {
                return ResourceManager.GetString("ReleaseLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desactivate a mode.
        /// </summary>
        public static string RemoveMode {
            get {
                return ResourceManager.GetString("RemoveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click.
        /// </summary>
        public static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables sending a special key : Return, F1 to F12, Suppr etc....
        /// </summary>
        public static string SendKeyProtocolDescription {
            get {
                return ResourceManager.GetString("SendKeyProtocolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action : .
        /// </summary>
        public static string SendKeyProtocolSubtitle {
            get {
                return ResourceManager.GetString("SendKeyProtocolSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Key (F11, Return, Suppr ...).
        /// </summary>
        public static string SendKeyProtocolTitle {
            get {
                return ResourceManager.GetString("SendKeyProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a mode as the current (and only) one.
        /// </summary>
        public static string SetMode {
            get {
                return ResourceManager.GetString("SetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the keyboard&apos;s help panel.
        /// </summary>
        public static string ShowHelpAction {
            get {
                return ResourceManager.GetString("ShowHelpAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle a mode.
        /// </summary>
        public static string ToggleMode {
            get {
                return ResourceManager.GetString("ToggleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Up {
            get {
                return ResourceManager.GetString("Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-Left.
        /// </summary>
        public static string UpLeft {
            get {
                return ResourceManager.GetString("UpLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-Right.
        /// </summary>
        public static string UpRight {
            get {
                return ResourceManager.GetString("UpRight", resourceCulture);
            }
        }
    }
}
