//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardPatcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardPatcher.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Azerty&quot; keyboard could not be found. This update can&apos;t be applied. Date : ({0}).
        /// </summary>
        internal static string AzertyKeyboardNotFound {
            get {
                return ResourceManager.GetString("AzertyKeyboardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the configuration window.
        /// </summary>
        internal static string DisplayConfigWindow {
            get {
                return ResourceManager.GetString("DisplayConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, don&apos;t try again.
        /// </summary>
        internal static string DontTryAgain {
            get {
                return ResourceManager.GetString("DontTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A keyboard update is available. 
        ///would you like to install it ? .
        /// </summary>
        internal static string KeyboardUpdateDescription {
            get {
                return ResourceManager.GetString("KeyboardUpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard update.
        /// </summary>
        internal static string KeyboardUpdateTitle {
            get {
                return ResourceManager.GetString("KeyboardUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;MinimizeHost&quot; key has already been added. This update is useless on this keyboard. Date : ({0}).
        /// </summary>
        internal static string MinimizeHostKeyAlreadyAdded {
            get {
                return ResourceManager.GetString("MinimizeHostKeyAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember my decision.
        /// </summary>
        internal static string RememberMyDecision {
            get {
                return ResourceManager.GetString("RememberMyDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyboard update has been cancelled for the following reason : 
        ///
        ///{0}
        ///
        ///Do you want to try launching this update again during the next launch ?.
        /// </summary>
        internal static string UpdateCancelledMsgBoxExplanation {
            get {
                return ResourceManager.GetString("UpdateCancelledMsgBoxExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keyboard update has been cancelled.
        /// </summary>
        internal static string UpdateCancelledTitle {
            get {
                return ResourceManager.GetString("UpdateCancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has cancelled the update. (Date: {0}).
        /// </summary>
        internal static string UserCancelled {
            get {
                return ResourceManager.GetString("UserCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
