//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardEditor.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardEditor.Resources.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Down arrow.
        /// </summary>
        internal static string BoldDownArrow {
            get {
                return ResourceManager.GetString("BoldDownArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Down left arrow.
        /// </summary>
        internal static string BoldDownLeftArrow {
            get {
                return ResourceManager.GetString("BoldDownLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Down right arrow.
        /// </summary>
        internal static string BoldDownRightArrow {
            get {
                return ResourceManager.GetString("BoldDownRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Left arrow.
        /// </summary>
        internal static string BoldLeftArrow {
            get {
                return ResourceManager.GetString("BoldLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Right arrow.
        /// </summary>
        internal static string BoldRightArrow {
            get {
                return ResourceManager.GetString("BoldRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Top left arrow.
        /// </summary>
        internal static string BoldTopLeftArrow {
            get {
                return ResourceManager.GetString("BoldTopLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Top right arrow.
        /// </summary>
        internal static string BoldTopRightArrow {
            get {
                return ResourceManager.GetString("BoldTopRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold Up arrow.
        /// </summary>
        internal static string BoldUpArrow {
            get {
                return ResourceManager.GetString("BoldUpArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps.
        /// </summary>
        internal static string Caps {
            get {
                return ResourceManager.GetString("Caps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double left click.
        /// </summary>
        internal static string DoubleLeftClick {
            get {
                return ResourceManager.GetString("DoubleLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop.
        /// </summary>
        internal static string DragDrop {
            get {
                return ResourceManager.GetString("DragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eye.
        /// </summary>
        internal static string Eye {
            get {
                return ResourceManager.GetString("Eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click.
        /// </summary>
        internal static string LeftClick {
            get {
                return ResourceManager.GetString("LeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse keyboard.
        /// </summary>
        internal static string MouseKeyboard {
            get {
                return ResourceManager.GetString("MouseKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padlock.
        /// </summary>
        internal static string Padlock {
            get {
                return ResourceManager.GetString("Padlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click.
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppr.
        /// </summary>
        internal static string Suppr {
            get {
                return ResourceManager.GetString("Suppr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string Tab {
            get {
                return ResourceManager.GetString("Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows logo.
        /// </summary>
        internal static string WindowsLogo {
            get {
                return ResourceManager.GetString("WindowsLogo", resourceCulture);
            }
        }
    }
}
