//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Host.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of active modules : .
        /// </summary>
        public static string ActiveModules {
            get {
                return ResourceManager.GetString("ActiveModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced configuration.
        /// </summary>
        public static string AdvancedAppConfig {
            get {
                return ResourceManager.GetString("AdvancedAppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Advanced user).
        /// </summary>
        public static string AdvancedUserNotice {
            get {
                return ResourceManager.GetString("AdvancedUserNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Configuration.
        /// </summary>
        public static string AppConfig {
            get {
                return ResourceManager.GetString("AppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string AppFeature {
            get {
                return ResourceManager.GetString("AppFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto clic feature configuration.
        /// </summary>
        public static string AutoClickConfig {
            get {
                return ResourceManager.GetString("AutoClickConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown duration (ms).
        /// </summary>
        public static string AutoClickCountDownDuration {
            get {
                return ResourceManager.GetString("AutoClickCountDownDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto click.
        /// </summary>
        public static string AutoClickSectionName {
            get {
                return ResourceManager.GetString("AutoClickSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a progress indicator above the pointer.
        /// </summary>
        public static string AutoClickShowMousePanelOption {
            get {
                return ResourceManager.GetString("AutoClickShowMousePanelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time before the countdown starts (ms).
        /// </summary>
        public static string AutoClickTimeBeforeCountDownStarts {
            get {
                return ResourceManager.GetString("AutoClickTimeBeforeCountDownStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiviKey - Standard.
        /// </summary>
        public static string CiviKey {
            get {
                return ResourceManager.GetString("CiviKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiviKey is running.
        /// </summary>
        public static string CKIsRunning {
            get {
                return ResourceManager.GetString("CKIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroller preview selector.
        /// </summary>
        public static string ClickTypeScrollerSelector {
            get {
                return ResourceManager.GetString("ClickTypeScrollerSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to click.
        /// </summary>
        public static string ClickTypeSelectorName {
            get {
                return ResourceManager.GetString("ClickTypeSelectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon !.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not implemented yet. We&apos;re working on it ! .
        /// </summary>
        public static string ComingSoonContent {
            get {
                return ResourceManager.GetString("ComingSoonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit CiviKey?.
        /// </summary>
        public static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address for the context is required..
        /// </summary>
        public static string ContextAddressRequired {
            get {
                return ResourceManager.GetString("ContextAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current context doesn&apos;t contain any keyboard definition. Please click on the picture to load another one..
        /// </summary>
        public static string ContextIsEmpty {
            get {
                return ResourceManager.GetString("ContextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now select a keyboard and start using CiviKey !.
        /// </summary>
        public static string ContextLoadedContent {
            get {
                return ResourceManager.GetString("ContextLoadedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context has been successfully loaded..
        /// </summary>
        public static string ContextLoadedTitle {
            get {
                return ResourceManager.GetString("ContextLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the call stack.
        /// </summary>
        public static string CopyError {
            get {
                return ResourceManager.GetString("CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the picture or on the new system tray icon to edit the configuration..
        /// </summary>
        public static string EditConfig {
            get {
                return ResourceManager.GetString("EditConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start keyboard skin editor.
        /// </summary>
        public static string EditSkin {
            get {
                return ResourceManager.GetString("EditSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable scrolling on the element.
        /// </summary>
        public static string EnableScrolling {
            get {
                return ResourceManager.GetString("EnableScrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the plugin startup, or given requirements cannot be fullfilled. We cannot give you more informations yet, we&apos;re working on it..
        /// </summary>
        public static string ErrorApplyingConfiguration {
            get {
                return ResourceManager.GetString("ErrorApplyingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has been raised !.
        /// </summary>
        public static string ExceptionNotificationTitle {
            get {
                return ResourceManager.GetString("ExceptionNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit CiviKey ?.
        /// </summary>
        public static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your configuration.
        /// </summary>
        public static string ExportConf {
            get {
                return ResourceManager.GetString("ExportConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export a keyboard.
        /// </summary>
        public static string ExportKeyboard {
            get {
                return ResourceManager.GetString("ExportKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string FeatureDisable {
            get {
                return ResourceManager.GetString("FeatureDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FeatureEnable {
            get {
                return ResourceManager.GetString("FeatureEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The System&apos;s configuration has been corrupted.
        /// </summary>
        public static string ForbiddenAction {
            get {
                return ResourceManager.GetString("ForbiddenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden action.
        /// </summary>
        public static string ForbiddenActionTitle {
            get {
                return ResourceManager.GetString("ForbiddenActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of modules which cannot be scrolled on : .
        /// </summary>
        public static string ForbiddenModules {
            get {
                return ResourceManager.GetString("ForbiddenModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbid scrolling on this element.
        /// </summary>
        public static string ForbidScrolling {
            get {
                return ResourceManager.GetString("ForbidScrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a keyboard.
        /// </summary>
        public static string ImportKeyboard {
            get {
                return ResourceManager.GetString("ImportKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current keyboard has changed.
        /// </summary>
        public static string KeyboardChanged {
            get {
                return ResourceManager.GetString("KeyboardChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current keyboard has changed. You&apos;re now using the keyboard nammed {0}..
        /// </summary>
        public static string KeyboardChangedContent {
            get {
                return ResourceManager.GetString("KeyboardChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard pointer.
        /// </summary>
        public static string KeyboardPointer {
            get {
                return ResourceManager.GetString("KeyboardPointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses a keyboard to move the mouse.
        /// </summary>
        public static string KeyboardPointerDescription {
            get {
                return ResourceManager.GetString("KeyboardPointerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboards.
        /// </summary>
        public static string Keyboards {
            get {
                return ResourceManager.GetString("Keyboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update CiviKey.
        /// </summary>
        public static string LaunchUpdate {
            get {
                return ResourceManager.GetString("LaunchUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a context.
        /// </summary>
        public static string LoadContext {
            get {
                return ResourceManager.GetString("LoadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a user configuration.
        /// </summary>
        public static string LoadUserConfig {
            get {
                return ResourceManager.GetString("LoadUserConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse scrolling type selection.
        /// </summary>
        public static string MouseScrollingSelection {
            get {
                return ResourceManager.GetString("MouseScrollingSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move mouse.
        /// </summary>
        public static string MoveMouse {
            get {
                return ResourceManager.GetString("MoveMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on {0:D}.
        /// </summary>
        public static string NewContextDisplayName {
            get {
                return ResourceManager.GetString("NewContextDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoPointingDevice {
            get {
                return ResourceManager.GetString("NoPointingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all pointing mecanisms.
        /// </summary>
        public static string NoPointingDeviceDescription {
            get {
                return ResourceManager.GetString("NoPointingDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects Explorer.
        /// </summary>
        public static string ObjectExplorer {
            get {
                return ResourceManager.GetString("ObjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced configurations.
        /// </summary>
        public static string OtherScrollConfig {
            get {
                return ResourceManager.GetString("OtherScrollConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oups !.
        /// </summary>
        public static string Oups {
            get {
                return ResourceManager.GetString("Oups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin called {0} can&apos;t be launched, would you like to start CiviKey without this plugin ?.
        /// </summary>
        public static string PluginThrewExceptionAtStart {
            get {
                return ResourceManager.GetString("PluginThrewExceptionAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while launching a plugin.
        /// </summary>
        public static string PluginThrewExceptionAtStartTitle {
            get {
                return ResourceManager.GetString("PluginThrewExceptionAtStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        public static string Radar {
            get {
                return ResourceManager.GetString("Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar configuration.
        /// </summary>
        public static string RadarConfiguration {
            get {
                return ResourceManager.GetString("RadarConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the pointer thanks to the &quot;radar&quot; mecanism.
        /// </summary>
        public static string RadarDescription {
            get {
                return ResourceManager.GetString("RadarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me when new updates are available.
        /// </summary>
        public static string RemindMeOfNewUpdates {
            get {
                return ResourceManager.GetString("RemindMeOfNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen scroler configuration.
        /// </summary>
        public static string ScreenScrollerConfiguration {
            get {
                return ResourceManager.GetString("ScreenScrollerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen scrolling.
        /// </summary>
        public static string ScreenScrolling {
            get {
                return ResourceManager.GetString("ScreenScrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a grid on the screen to move the mouse pointer.
        /// </summary>
        public static string ScreenScrollingDescription {
            get {
                return ResourceManager.GetString("ScreenScrollingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollable modules.
        /// </summary>
        public static string ScrollableElements {
            get {
                return ResourceManager.GetString("ScrollableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit scrolling configuration.
        /// </summary>
        public static string ScrollConfig {
            get {
                return ResourceManager.GetString("ScrollConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Scrolling.
        /// </summary>
        public static string Scrolling {
            get {
                return ResourceManager.GetString("Scrolling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling speed.
        /// </summary>
        public static string ScrollingSpeed {
            get {
                return ResourceManager.GetString("ScrollingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrolling strategy :.
        /// </summary>
        public static string ScrollingStrategy {
            get {
                return ResourceManager.GetString("ScrollingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import or Export a keyboard.
        /// </summary>
        public static string ShareKeyboard {
            get {
                return ResourceManager.GetString("ShareKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the editor panel.
        /// </summary>
        public static string ShowEditor {
            get {
                return ResourceManager.GetString("ShowEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Systray icon.
        /// </summary>
        public static string ShowSystrayIcon {
            get {
                return ResourceManager.GetString("ShowSystrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Taskbar icon.
        /// </summary>
        public static string ShowTaskbarIcon {
            get {
                return ResourceManager.GetString("ShowTaskbarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the autohide feature.
        /// </summary>
        public static string SkinAutohideFeature {
            get {
                return ResourceManager.GetString("SkinAutohideFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout until the skin disappear (in ms).
        /// </summary>
        public static string SkinAutohideTimeout {
            get {
                return ResourceManager.GetString("SkinAutohideTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic configuration.
        /// </summary>
        public static string SkinBasicConfig {
            get {
                return ResourceManager.GetString("SkinBasicConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On screen keyboard configuration.
        /// </summary>
        public static string SkinConfig {
            get {
                return ResourceManager.GetString("SkinConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard edition.
        /// </summary>
        public static string SkinEditorSectionName {
            get {
                return ResourceManager.GetString("SkinEditorSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on screen keyboard.
        /// </summary>
        public static string SkinSectionName {
            get {
                return ResourceManager.GetString("SkinSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit on screen keyboard visual configuration.
        /// </summary>
        public static string SkinViewConfig {
            get {
                return ResourceManager.GetString("SkinViewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo scrolling speed.
        /// </summary>
        public static string TurboScrollingSpeed {
            get {
                return ResourceManager.GetString("TurboScrollingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the loading. CiviKey cannot load the chosen context..
        /// </summary>
        public static string UnableToLoadContext {
            get {
                return ResourceManager.GetString("UnableToLoadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not scrollable modules.
        /// </summary>
        public static string UnScrollableElements {
            get {
                return ResourceManager.GetString("UnScrollableElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of CiviKey is available, would you like to launch the upgraded now ?.
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Prediction configuration.
        /// </summary>
        public static string WordPredictionConfig {
            get {
                return ResourceManager.GetString("WordPredictionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la fenêtre de l&apos;éditeur de prédiction.
        /// </summary>
        public static string WordPredictionDisplayPredictionEditorWindow {
            get {
                return ResourceManager.GetString("WordPredictionDisplayPredictionEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters already suggested words.
        /// </summary>
        public static string WordPredictionFilterAlreadySuggestedWord {
            get {
                return ResourceManager.GetString("WordPredictionFilterAlreadySuggestedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after predicted words.
        /// </summary>
        public static string WordPredictionInsertSpace {
            get {
                return ResourceManager.GetString("WordPredictionInsertSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max suggested words (maximum).
        /// </summary>
        public static string WordPredictionMaxSuggestedWords {
            get {
                return ResourceManager.GetString("WordPredictionMaxSuggestedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Prediction.
        /// </summary>
        public static string WordPredictionSectionName {
            get {
                return ResourceManager.GetString("WordPredictionSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses semantic prediction.
        /// </summary>
        public static string WordPredictionUseSemanticPrediction {
            get {
                return ResourceManager.GetString("WordPredictionUseSemanticPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
