//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Host.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Advanced user).
        /// </summary>
        public static string AdvancedUserNotice {
            get {
                return ResourceManager.GetString("AdvancedUserNotice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string FeatureEnable
        {
            get
            {
                return ResourceManager.GetString( "FeatureEnable", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application Configuration.
        /// </summary>
        public static string AppConfig {
            get {
                return ResourceManager.GetString("AppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string AppFeature {
            get {
                return ResourceManager.GetString("AppFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto clic feature configuration.
        /// </summary>
        public static string AutoClickConfig {
            get {
                return ResourceManager.GetString("AutoClickConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown duration.
        /// </summary>
        public static string AutoClickCountDownDuration {
            get {
                return ResourceManager.GetString("AutoClickCountDownDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto click.
        /// </summary>
        public static string AutoClickSectionName {
            get {
                return ResourceManager.GetString("AutoClickSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a progress indicator above the pointer.
        /// </summary>
        public static string AutoClickShowMousePanelOption {
            get {
                return ResourceManager.GetString("AutoClickShowMousePanelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time before the countdown starts.
        /// </summary>
        public static string AutoClickTimeBeforeCountDownStarts {
            get {
                return ResourceManager.GetString("AutoClickTimeBeforeCountDownStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiviKey - Standard.
        /// </summary>
        public static string CiviKey {
            get {
                return ResourceManager.GetString("CiviKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CiviKey is running.
        /// </summary>
        public static string CKIsRunning {
            get {
                return ResourceManager.GetString("CKIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon !.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not implemented yet. We&apos;re working on it ! .
        /// </summary>
        public static string ComingSoonContent {
            get {
                return ResourceManager.GetString("ComingSoonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit CiviKey?.
        /// </summary>
        public static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current context doesn&apos;t contain any keyboard definition. Please click on the picture to load another one..
        /// </summary>
        public static string ContextIsEmpty {
            get {
                return ResourceManager.GetString("ContextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now select a keyboard and start using CiviKey !.
        /// </summary>
        public static string ContextLoadedContent {
            get {
                return ResourceManager.GetString("ContextLoadedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context has been successfully loaded..
        /// </summary>
        public static string ContextLoadedTitle {
            get {
                return ResourceManager.GetString("ContextLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the call stack.
        /// </summary>
        public static string CopyError {
            get {
                return ResourceManager.GetString("CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the picture or on the new system tray icon to edit the configuration..
        /// </summary>
        public static string EditConfig {
            get {
                return ResourceManager.GetString("EditConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start keyboard skin editor.
        /// </summary>
        public static string EditSkin {
            get {
                return ResourceManager.GetString("EditSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the plugin startup, or given requirements cannot be fullfilled. We cannot give you more informations yet, we&apos;re working on it..
        /// </summary>
        public static string ErrorApplyingConfiguration {
            get {
                return ResourceManager.GetString("ErrorApplyingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception has been raised !.
        /// </summary>
        public static string ExceptionNotificationTitle {
            get {
                return ResourceManager.GetString("ExceptionNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The System&apos;s configuration has been corrupted.
        /// </summary>
        public static string ForbiddenAction {
            get {
                return ResourceManager.GetString("ForbiddenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden action.
        /// </summary>
        public static string ForbiddenActionTitle {
            get {
                return ResourceManager.GetString("ForbiddenActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current keyboard has changed.
        /// </summary>
        public static string KeyboardChanged {
            get {
                return ResourceManager.GetString("KeyboardChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current keyboard has changed. You&apos;re now using the keyboard nammed {0}..
        /// </summary>
        public static string KeyboardChangedContent {
            get {
                return ResourceManager.GetString("KeyboardChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboards.
        /// </summary>
        public static string Keyboards {
            get {
                return ResourceManager.GetString("Keyboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a context.
        /// </summary>
        public static string LoadContext {
            get {
                return ResourceManager.GetString("LoadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a user configuration.
        /// </summary>
        public static string LoadUserConfig {
            get {
                return ResourceManager.GetString("LoadUserConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects Explorer.
        /// </summary>
        public static string ObjectExplorer {
            get {
                return ResourceManager.GetString("ObjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oups !.
        /// </summary>
        public static string Oups {
            get {
                return ResourceManager.GetString("Oups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin called {0} can&apos;t be launched, would you like to start CiviKey without this plugin ?.
        /// </summary>
        public static string PluginThrewExceptionAtStart {
            get {
                return ResourceManager.GetString("PluginThrewExceptionAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while launching a plugin.
        /// </summary>
        public static string PluginThrewExceptionAtStartTitle {
            get {
                return ResourceManager.GetString("PluginThrewExceptionAtStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Systray icon.
        /// </summary>
        public static string ShowSystrayIcon {
            get {
                return ResourceManager.GetString("ShowSystrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Taskbar icon.
        /// </summary>
        public static string ShowTaskbarIcon {
            get {
                return ResourceManager.GetString("ShowTaskbarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the autohide feature.
        /// </summary>
        public static string SkinAutohideFeature {
            get {
                return ResourceManager.GetString("SkinAutohideFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout until the skin disappear (in ms).
        /// </summary>
        public static string SkinAutohideTimeout {
            get {
                return ResourceManager.GetString("SkinAutohideTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On screen keyboard configuration.
        /// </summary>
        public static string SkinConfig {
            get {
                return ResourceManager.GetString("SkinConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on screen keyboard.
        /// </summary>
        public static string SkinSectionName {
            get {
                return ResourceManager.GetString("SkinSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit on screen keyboard visual configuration.
        /// </summary>
        public static string SkinViewConfig {
            get {
                return ResourceManager.GetString("SkinViewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the loading. CiviKey cannot load the chosen context..
        /// </summary>
        public static string UnableToLoadContext {
            get {
                return ResourceManager.GetString("UnableToLoadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of CiviKey is available, would you like to launch the upgraded now ?.
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
    }
}
