//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Host.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Host.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Advanced configuration.
        /// </summary>
        public static string AdvancedAppConfig {
            get {
                return ResourceManager.GetString("AdvancedAppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (Advanced user).
        /// </summary>
        public static string AdvancedUserNotice {
            get {
                return ResourceManager.GetString("AdvancedUserNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application Configuration.
        /// </summary>
        public static string AppConfig {
            get {
                return ResourceManager.GetString("AppConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Features.
        /// </summary>
        public static string AppFeature {
            get {
                return ResourceManager.GetString("AppFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto clic feature configuration.
        /// </summary>
        public static string AutoClickConfig {
            get {
                return ResourceManager.GetString("AutoClickConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Countdown duration.
        /// </summary>
        public static string AutoClickCountDownDuration {
            get {
                return ResourceManager.GetString("AutoClickCountDownDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à auto click.
        /// </summary>
        public static string AutoClickSectionName {
            get {
                return ResourceManager.GetString("AutoClickSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show a progress indicator above the pointer.
        /// </summary>
        public static string AutoClickShowMousePanelOption {
            get {
                return ResourceManager.GetString("AutoClickShowMousePanelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time before the countdown starts.
        /// </summary>
        public static string AutoClickTimeBeforeCountDownStarts {
            get {
                return ResourceManager.GetString("AutoClickTimeBeforeCountDownStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CiviKey - Standard.
        /// </summary>
        public static string CiviKey {
            get {
                return ResourceManager.GetString("CiviKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CiviKey is running.
        /// </summary>
        public static string CKIsRunning {
            get {
                return ResourceManager.GetString("CKIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coming soon !.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This feature is not implemented yet. We&apos;re working on it ! .
        /// </summary>
        public static string ComingSoonContent {
            get {
                return ResourceManager.GetString("ComingSoonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to quit CiviKey?.
        /// </summary>
        public static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An address for the context is required..
        /// </summary>
        public static string ContextAddressRequired {
            get {
                return ResourceManager.GetString("ContextAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current context doesn&apos;t contain any keyboard definition. Please click on the picture to load another one..
        /// </summary>
        public static string ContextIsEmpty {
            get {
                return ResourceManager.GetString("ContextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can now select a keyboard and start using CiviKey !.
        /// </summary>
        public static string ContextLoadedContent {
            get {
                return ResourceManager.GetString("ContextLoadedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The context has been successfully loaded..
        /// </summary>
        public static string ContextLoadedTitle {
            get {
                return ResourceManager.GetString("ContextLoadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy the call stack.
        /// </summary>
        public static string CopyError {
            get {
                return ResourceManager.GetString("CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click on the picture or on the new system tray icon to edit the configuration..
        /// </summary>
        public static string EditConfig {
            get {
                return ResourceManager.GetString("EditConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start keyboard skin editor.
        /// </summary>
        public static string EditSkin {
            get {
                return ResourceManager.GetString("EditSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during the plugin startup, or given requirements cannot be fullfilled. We cannot give you more informations yet, we&apos;re working on it..
        /// </summary>
        public static string ErrorApplyingConfiguration {
            get {
                return ResourceManager.GetString("ErrorApplyingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An exception has been raised !.
        /// </summary>
        public static string ExceptionNotificationTitle {
            get {
                return ResourceManager.GetString("ExceptionNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to exit CiviKey ?.
        /// </summary>
        public static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disable.
        /// </summary>
        public static string FeatureDisable {
            get {
                return ResourceManager.GetString("FeatureDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable.
        /// </summary>
        public static string FeatureEnable {
            get {
                return ResourceManager.GetString("FeatureEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The System&apos;s configuration has been corrupted.
        /// </summary>
        public static string ForbiddenAction {
            get {
                return ResourceManager.GetString("ForbiddenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forbidden action.
        /// </summary>
        public static string ForbiddenActionTitle {
            get {
                return ResourceManager.GetString("ForbiddenActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current keyboard has changed.
        /// </summary>
        public static string KeyboardChanged {
            get {
                return ResourceManager.GetString("KeyboardChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current keyboard has changed. You&apos;re now using the keyboard nammed {0}..
        /// </summary>
        public static string KeyboardChangedContent {
            get {
                return ResourceManager.GetString("KeyboardChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboards.
        /// </summary>
        public static string Keyboards {
            get {
                return ResourceManager.GetString("Keyboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update CiviKey.
        /// </summary>
        public static string LaunchUpdate {
            get {
                return ResourceManager.GetString("LaunchUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load a context.
        /// </summary>
        public static string LoadContext {
            get {
                return ResourceManager.GetString("LoadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Load a user configuration.
        /// </summary>
        public static string LoadUserConfig {
            get {
                return ResourceManager.GetString("LoadUserConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Created on {0:D}.
        /// </summary>
        public static string NewContextDisplayName {
            get {
                return ResourceManager.GetString("NewContextDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objects Explorer.
        /// </summary>
        public static string ObjectExplorer {
            get {
                return ResourceManager.GetString("ObjectExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oups !.
        /// </summary>
        public static string Oups {
            get {
                return ResourceManager.GetString("Oups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The plugin called {0} can&apos;t be launched, would you like to start CiviKey without this plugin ?.
        /// </summary>
        public static string PluginThrewExceptionAtStart {
            get {
                return ResourceManager.GetString("PluginThrewExceptionAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while launching a plugin.
        /// </summary>
        public static string PluginThrewExceptionAtStartTitle {
            get {
                return ResourceManager.GetString("PluginThrewExceptionAtStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remind me when new updates are available.
        /// </summary>
        public static string RemindMeOfNewUpdates {
            get {
                return ResourceManager.GetString("RemindMeOfNewUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit scrolling configuration.
        /// </summary>
        public static string ScrollConfig {
            get {
                return ResourceManager.GetString("ScrollConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scrolling.
        /// </summary>
        public static string ScrollingSectionName {
            get {
                return ResourceManager.GetString("ScrollingSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Systray icon.
        /// </summary>
        public static string ShowSystrayIcon {
            get {
                return ResourceManager.GetString("ShowSystrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Taskbar icon.
        /// </summary>
        public static string ShowTaskbarIcon {
            get {
                return ResourceManager.GetString("ShowTaskbarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enable the autohide feature.
        /// </summary>
        public static string SkinAutohideFeature {
            get {
                return ResourceManager.GetString("SkinAutohideFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timeout until the skin disappear (in ms).
        /// </summary>
        public static string SkinAutohideTimeout {
            get {
                return ResourceManager.GetString("SkinAutohideTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Basic configuration.
        /// </summary>
        public static string SkinBasicConfig {
            get {
                return ResourceManager.GetString("SkinBasicConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On screen keyboard configuration.
        /// </summary>
        public static string SkinConfig {
            get {
                return ResourceManager.GetString("SkinConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard edition.
        /// </summary>
        public static string SkinEditorSectionName {
            get {
                return ResourceManager.GetString("SkinEditorSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à on screen keyboard.
        /// </summary>
        public static string SkinSectionName {
            get {
                return ResourceManager.GetString("SkinSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit on screen keyboard visual configuration.
        /// </summary>
        public static string SkinViewConfig {
            get {
                return ResourceManager.GetString("SkinViewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occured during the loading. CiviKey cannot load the chosen context..
        /// </summary>
        public static string UnableToLoadContext {
            get {
                return ResourceManager.GetString("UnableToLoadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An update is available.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new version of CiviKey is available, would you like to launch the upgraded now ?.
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word Prediction configuration.
        /// </summary>
        public static string WordPredictionConfig {
            get {
                return ResourceManager.GetString("WordPredictionConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afficher la fenêtre de l&apos;éditeur de prédiction.
        /// </summary>
        public static string WordPredictionDisplayPredictionEditorWindow {
            get {
                return ResourceManager.GetString("WordPredictionDisplayPredictionEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filters already suggested words.
        /// </summary>
        public static string WordPredictionFilterAlreadySuggestedWord {
            get {
                return ResourceManager.GetString("WordPredictionFilterAlreadySuggestedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert space after predicted words.
        /// </summary>
        public static string WordPredictionInsertSpace {
            get {
                return ResourceManager.GetString("WordPredictionInsertSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Max suggested words (maximum).
        /// </summary>
        public static string WordPredictionMaxSuggestedWords {
            get {
                return ResourceManager.GetString("WordPredictionMaxSuggestedWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word Prediction.
        /// </summary>
        public static string WordPredictionSectionName {
            get {
                return ResourceManager.GetString("WordPredictionSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uses semantic prediction.
        /// </summary>
        public static string WordPredictionUseSemanticPrediction {
            get {
                return ResourceManager.GetString("WordPredictionUseSemanticPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
