//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CK.Config.UI.Config.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string Accessibility {
            get {
                return ResourceManager.GetString("Accessibility", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon AccessibilityIco {
            get {
                object obj = ResourceManager.GetObject("AccessibilityIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutomaticStart.
        /// </summary>
        internal static string automatic {
            get {
                return ResourceManager.GetString("automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the dependency map.
        /// </summary>
        internal static string CVKLoaderDependencing {
            get {
                return ResourceManager.GetString("CVKLoaderDependencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency map done.
        /// </summary>
        internal static string CVKLoaderDependencingDone {
            get {
                return ResourceManager.GetString("CVKLoaderDependencingDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching the CK.
        /// </summary>
        internal static string CVKLoaderLaunchingCVK {
            get {
                return ResourceManager.GetString("CVKLoaderLaunchingCVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the context.
        /// </summary>
        internal static string CVKLoaderLoadingContext {
            get {
                return ResourceManager.GetString("CVKLoaderLoadingContext", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CVKSplashScreenS {
            get {
                object obj = ResourceManager.GetObject("CVKSplashScreenS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap danger {
            get {
                object obj = ResourceManager.GetObject("danger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DegradeBlue {
            get {
                object obj = ResourceManager.GetObject("DegradeBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Degrader {
            get {
                object obj = ResourceManager.GetObject("Degrader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string editor {
            get {
                return ResourceManager.GetString("editor", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon logo_cvk {
            get {
                object obj = ResourceManager.GetObject("logo_cvk", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_cvk_32x32 {
            get {
                object obj = ResourceManager.GetObject("logo_cvk_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_cvk_48x48 {
            get {
                object obj = ResourceManager.GetObject("logo_cvk_48x48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo_cvk_64x64 {
            get {
                object obj = ResourceManager.GetObject("logo_cvk_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string manual {
            get {
                return ResourceManager.GetString("manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscelaneous.
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon MiscIco {
            get {
                object obj = ResourceManager.GetObject("MiscIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictor.
        /// </summary>
        internal static string Predictors {
            get {
                return ResourceManager.GetString("Predictors", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon PredictorsIco {
            get {
                object obj = ResourceManager.GetObject("PredictorsIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Run {
            get {
                object obj = ResourceManager.GetObject("Run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string startP {
            get {
                return ResourceManager.GetString("startP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stopP {
            get {
                return ResourceManager.GetString("stopP", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap thankBG {
            get {
                object obj = ResourceManager.GetObject("thankBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tick {
            get {
                object obj = ResourceManager.GetObject("Tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Vide {
            get {
                object obj = ResourceManager.GetObject("Vide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        internal static string Visual {
            get {
                return ResourceManager.GetString("Visual", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon VisualIco {
            get {
                object obj = ResourceManager.GetObject("VisualIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
