//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContextEditor.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can exit the wizard if you have no other modifications to make..
        /// </summary>
        internal static string EndingStepQuitDesc {
            get {
                return ResourceManager.GetString("EndingStepQuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can go back to the beginning of the wizard if you want to modify another keyboard..
        /// </summary>
        internal static string EndingStepStartOverDesc {
            get {
                return ResourceManager.GetString("EndingStepStartOverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the current keyboard ({0}).
        /// </summary>
        internal static string HomeEditCurrentKeyboard {
            get {
                return ResourceManager.GetString("HomeEditCurrentKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit easily the currently used keyboard..
        /// </summary>
        internal static string HomeEditCurrentKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditCurrentKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new keyboard.
        /// </summary>
        internal static string HomeEditNewKeyboard {
            get {
                return ResourceManager.GetString("HomeEditNewKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a keyboard from scratch.
        /// </summary>
        internal static string HomeEditNewKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditNewKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose another keyboard to modify.
        /// </summary>
        internal static string HomeEditOtherKeyboard {
            get {
                return ResourceManager.GetString("HomeEditOtherKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify another keyboard or start from an existing keyboard to create a new one..
        /// </summary>
        internal static string HomeEditOtherKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditOtherKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CiviKey&apos;s keyboard creation and modification wizard.
        ///You can choose between the three following actions to chose the keyboard you want to modify..
        /// </summary>
        internal static string HomeStepDescription {
            get {
                return ResourceManager.GetString("HomeStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard creation and modification.
        /// </summary>
        internal static string HomeStepTitle {
            get {
                return ResourceManager.GetString("HomeStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going back is going to erase the modifications made until now.
        ///Are you sure you want to go back ?.
        /// </summary>
        internal static string KeyboardProfileBackPopInDesc {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, stay on this page.
        /// </summary>
        internal static string KeyboardProfileBackPopInNo {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel modifications.
        /// </summary>
        internal static string KeyboardProfileBackPopInTitle {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, revert modifications.
        /// </summary>
        internal static string KeyboardProfileBackPopInYes {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page enables you to modify the basic properties of a keyboard : its name, width and height..
        /// </summary>
        internal static string KeyboardProfileDesc {
            get {
                return ResourceManager.GetString("KeyboardProfileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic keyboard properties edition.
        /// </summary>
        internal static string KeyboardProfileTitle {
            get {
                return ResourceManager.GetString("KeyboardProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to save your modifications on the keyboard named {0}.
        ///Are you sure that you want to erase this existing keyboard ?.
        /// </summary>
        internal static string SaveAsStepPopInDesc {
            get {
                return ResourceManager.GetString("SaveAsStepPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase an existing keyboard.
        /// </summary>
        internal static string SaveAsStepPopInTitle {
            get {
                return ResourceManager.GetString("SaveAsStepPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all modifications made on this keyboard and quit the wizard..
        /// </summary>
        internal static string SavingStepCancelAndQuitDesc {
            get {
                return ResourceManager.GetString("SavingStepCancelAndQuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and quit.
        /// </summary>
        internal static string SavingStepCancelAndQuitTitle {
            get {
                return ResourceManager.GetString("SavingStepCancelAndQuitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all modifications made on this keyboard and go back to the beginning of the wizard..
        /// </summary>
        internal static string SavingStepCancelAndRestartDesc {
            get {
                return ResourceManager.GetString("SavingStepCancelAndRestartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and restart.
        /// </summary>
        internal static string SavingStepCancelAndRestartTitle {
            get {
                return ResourceManager.GetString("SavingStepCancelAndRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the modifications made on a new keyboard or another existing one..
        /// </summary>
        internal static string SavingStepSaveAsDesc {
            get {
                return ResourceManager.GetString("SavingStepSaveAsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string SavingStepSaveAsTitle {
            get {
                return ResourceManager.GetString("SavingStepSaveAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the modifications made on this keyboard..
        /// </summary>
        internal static string SavingStepSaveDesc {
            get {
                return ResourceManager.GetString("SavingStepSaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavingStepSaveTitle {
            get {
                return ResourceManager.GetString("SavingStepSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        internal static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard creation wizard.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
