//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardEditor.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ContentSection {
            get {
                return ResourceManager.GetString("ContentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default mode.
        /// </summary>
        public static string DefaultMode {
            get {
                return ResourceManager.GetString("DefaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default zone.
        /// </summary>
        public static string DefaultZone {
            get {
                return ResourceManager.GetString("DefaultZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a key.
        /// </summary>
        public static string DeleteKey {
            get {
                return ResourceManager.GetString("DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this key ?.
        /// </summary>
        public static string DeleteKeyConfirmation {
            get {
                return ResourceManager.GetString("DeleteKeyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the zone.
        /// </summary>
        public static string DeleteKeys {
            get {
                return ResourceManager.GetString("DeleteKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a zone.
        /// </summary>
        public static string DeleteZone {
            get {
                return ResourceManager.GetString("DeleteZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete this zone ?.
        /// </summary>
        public static string DeleteZoneConfirmation {
            get {
                return ResourceManager.GetString("DeleteZoneConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string DesignSection {
            get {
                return ResourceManager.GetString("DesignSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction : .
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your modifications have been correctly saved, you can now exit the wizard or restart the wizard to modify another keyboard..
        /// </summary>
        public static string EndingStepDesc {
            get {
                return ResourceManager.GetString("EndingStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can exit the wizard if you have no other modifications to make..
        /// </summary>
        public static string EndingStepQuitDesc {
            get {
                return ResourceManager.GetString("EndingStepQuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can go back to the beginning of the wizard if you want to modify another keyboard..
        /// </summary>
        public static string EndingStepStartOverDesc {
            get {
                return ResourceManager.GetString("EndingStepStartOverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications saved.
        /// </summary>
        public static string EndingStepTitle {
            get {
                return ResourceManager.GetString("EndingStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string FileLauncher {
            get {
                return ResourceManager.GetString("FileLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file from your computer.
        /// </summary>
        public static string FileLauncherBrowse {
            get {
                return ResourceManager.GetString("FileLauncherBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An installed application.
        /// </summary>
        public static string FileLauncherInstalledApps {
            get {
                return ResourceManager.GetString("FileLauncherInstalledApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete one of your keyboards.
        /// </summary>
        public static string HomeDestroyKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeDestroyKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a keyboard.
        /// </summary>
        public static string HomeDestroyKeyboardTitle {
            get {
                return ResourceManager.GetString("HomeDestroyKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the current keyboard.
        /// </summary>
        public static string HomeEditCurrentKeyboard {
            get {
                return ResourceManager.GetString("HomeEditCurrentKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit easily the currently used keyboard..
        /// </summary>
        public static string HomeEditCurrentKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditCurrentKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new keyboard.
        /// </summary>
        public static string HomeEditNewKeyboard {
            get {
                return ResourceManager.GetString("HomeEditNewKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a keyboard from scratch.
        /// </summary>
        public static string HomeEditNewKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditNewKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose another keyboard to modify.
        /// </summary>
        public static string HomeEditOtherKeyboard {
            get {
                return ResourceManager.GetString("HomeEditOtherKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify another keyboard or start from an existing keyboard to create a new one..
        /// </summary>
        public static string HomeEditOtherKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditOtherKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to CiviKey&apos;s keyboard creation and modification wizard.
        ///You can choose between the four following actions to chose the keyboard you want to modify..
        /// </summary>
        public static string HomeStepDescription {
            get {
                return ResourceManager.GetString("HomeStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard creation and modification.
        /// </summary>
        public static string HomeStepTitle {
            get {
                return ResourceManager.GetString("HomeStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To delete a keybaord, select the keyboard you want removed, then press &quot;Next&quot;..
        /// </summary>
        public static string KeyboardDeletionListStepDesc {
            get {
                return ResourceManager.GetString("KeyboardDeletionListStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard deletion.
        /// </summary>
        public static string KeyboardDeletionListStepTitle {
            get {
                return ResourceManager.GetString("KeyboardDeletionListStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through this page you can add, delete or modify any key of the keyboard.
        ///Modifications will be saved during the next step..
        /// </summary>
        public static string KeyboardEditionStepDesc {
            get {
                return ResourceManager.GetString("KeyboardEditionStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard modification : {0}.
        /// </summary>
        public static string KeyboardEditionStepTitle {
            get {
                return ResourceManager.GetString("KeyboardEditionStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose among the existing keyboard the one that you want to modify, or from which you want to start to create a new keyboard..
        /// </summary>
        public static string KeyboardListStepDesc {
            get {
                return ResourceManager.GetString("KeyboardListStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing keyboards list.
        /// </summary>
        public static string KeyboardListStepTitle {
            get {
                return ResourceManager.GetString("KeyboardListStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going back is going to erase the modifications made until now.
        ///Are you sure you want to go back ?.
        /// </summary>
        public static string KeyboardProfileBackPopInDesc {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, stay on this page.
        /// </summary>
        public static string KeyboardProfileBackPopInNo {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel modifications.
        /// </summary>
        public static string KeyboardProfileBackPopInTitle {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, revert modifications.
        /// </summary>
        public static string KeyboardProfileBackPopInYes {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page enables you to modify the name of the keyboard..
        /// </summary>
        public static string KeyboardProfileDesc {
            get {
                return ResourceManager.GetString("KeyboardProfileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard&apos;s name edition.
        /// </summary>
        public static string KeyboardProfileTitle {
            get {
                return ResourceManager.GetString("KeyboardProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of each move (pixels) .
        /// </summary>
        public static string MouseMoveSpeed {
            get {
                return ResourceManager.GetString("MouseMoveSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new command : .
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot chain chaining actions..
        /// </summary>
        public static string NoChaining {
            get {
                return ResourceManager.GetString("NoChaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can either select an existing keyboard ot erase it, or type a new keyboard name to save your modifications under a new keyboard.
        ///If you have started your modifications with an existing keyboard, its former state will be re-established..
        /// </summary>
        public static string SaveAsStepDesc {
            get {
                return ResourceManager.GetString("SaveAsStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to save your modifications on the keyboard named {0}.
        ///Are you sure that you want to erase this existing keyboard ?.
        /// </summary>
        public static string SaveAsStepPopInDesc {
            get {
                return ResourceManager.GetString("SaveAsStepPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erase an existing keyboard.
        /// </summary>
        public static string SaveAsStepPopInTitle {
            get {
                return ResourceManager.GetString("SaveAsStepPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as... step.
        /// </summary>
        public static string SaveAsStepTitle {
            get {
                return ResourceManager.GetString("SaveAsStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the keys.
        /// </summary>
        public static string SaveKeys {
            get {
                return ResourceManager.GetString("SaveKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all modifications made on this keyboard and quit the wizard..
        /// </summary>
        public static string SavingStepCancelAndQuitDesc {
            get {
                return ResourceManager.GetString("SavingStepCancelAndQuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and quit.
        /// </summary>
        public static string SavingStepCancelAndQuitTitle {
            get {
                return ResourceManager.GetString("SavingStepCancelAndQuitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all modifications made on this keyboard and go back to the beginning of the wizard..
        /// </summary>
        public static string SavingStepCancelAndRestartDesc {
            get {
                return ResourceManager.GetString("SavingStepCancelAndRestartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and restart.
        /// </summary>
        public static string SavingStepCancelAndRestartTitle {
            get {
                return ResourceManager.GetString("SavingStepCancelAndRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now choose where you want to save the modifications you just made; on the &quot;{0}&quot; keyboard, or on another one..
        /// </summary>
        public static string SavingStepDesc {
            get {
                return ResourceManager.GetString("SavingStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the modifications made on a new keyboard or another existing one..
        /// </summary>
        public static string SavingStepSaveAsDesc {
            get {
                return ResourceManager.GetString("SavingStepSaveAsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string SavingStepSaveAsTitle {
            get {
                return ResourceManager.GetString("SavingStepSaveAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the modifications made on this keyboard..
        /// </summary>
        public static string SavingStepSaveDesc {
            get {
                return ResourceManager.GetString("SavingStepSaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SavingStepSaveTitle {
            get {
                return ResourceManager.GetString("SavingStepSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving step.
        /// </summary>
        public static string SavingStepTitle {
            get {
                return ResourceManager.GetString("SavingStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop over screen .
        /// </summary>
        public static string SnakeMode {
            get {
                return ResourceManager.GetString("SnakeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        public static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String to send : .
        /// </summary>
        public static string StringToSend {
            get {
                return ResourceManager.GetString("StringToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a placeholder.
        /// </summary>
        public static string TextTemplateAdd {
            get {
                return ResourceManager.GetString("TextTemplateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit a template.
        /// </summary>
        public static string TextTemplateTitle {
            get {
                return ResourceManager.GetString("TextTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard creation wizard.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to close the keyboard edition wizard. 
        ///
        ///Are you sure that you want to do that ? All modifications unsaved will be lost..
        /// </summary>
        public static string WizardExitPopInDesc {
            get {
                return ResourceManager.GetString("WizardExitPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting the wizard.
        /// </summary>
        public static string WizardExitPopInTitle {
            get {
                return ResourceManager.GetString("WizardExitPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
