//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardEditor.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Content.
        /// </summary>
        internal static string ContentSection {
            get {
                return ResourceManager.GetString("ContentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default mode.
        /// </summary>
        internal static string DefaultMode {
            get {
                return ResourceManager.GetString("DefaultMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default zone.
        /// </summary>
        internal static string DefaultZone {
            get {
                return ResourceManager.GetString("DefaultZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a key.
        /// </summary>
        internal static string DeleteKey {
            get {
                return ResourceManager.GetString("DeleteKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure that you want to delete this key ?.
        /// </summary>
        internal static string DeleteKeyConfirmation {
            get {
                return ResourceManager.GetString("DeleteKeyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the keys.
        /// </summary>
        internal static string DeleteKeys {
            get {
                return ResourceManager.GetString("DeleteKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a zone.
        /// </summary>
        internal static string DeleteZone {
            get {
                return ResourceManager.GetString("DeleteZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are yout sure that you want to delete this zone ?.
        /// </summary>
        internal static string DeleteZoneConfirmation {
            get {
                return ResourceManager.GetString("DeleteZoneConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Design.
        /// </summary>
        internal static string DesignSection {
            get {
                return ResourceManager.GetString("DesignSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your modifications have been correctly saved, you can now exit the wizard or restart the wizard to modify another keyboard..
        /// </summary>
        internal static string EndingStepDesc {
            get {
                return ResourceManager.GetString("EndingStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can exit the wizard if you have no other modifications to make..
        /// </summary>
        internal static string EndingStepQuitDesc {
            get {
                return ResourceManager.GetString("EndingStepQuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can go back to the beginning of the wizard if you want to modify another keyboard..
        /// </summary>
        internal static string EndingStepStartOverDesc {
            get {
                return ResourceManager.GetString("EndingStepStartOverDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifications saved.
        /// </summary>
        internal static string EndingStepTitle {
            get {
                return ResourceManager.GetString("EndingStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete one of your keyboards.
        /// </summary>
        internal static string HomeDestroyKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeDestroyKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a keyboard.
        /// </summary>
        internal static string HomeDestroyKeyboardTitle {
            get {
                return ResourceManager.GetString("HomeDestroyKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit the current keyboard.
        /// </summary>
        internal static string HomeEditCurrentKeyboard {
            get {
                return ResourceManager.GetString("HomeEditCurrentKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit easily the currently used keyboard..
        /// </summary>
        internal static string HomeEditCurrentKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditCurrentKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new keyboard.
        /// </summary>
        internal static string HomeEditNewKeyboard {
            get {
                return ResourceManager.GetString("HomeEditNewKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a keyboard from scratch.
        /// </summary>
        internal static string HomeEditNewKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditNewKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose another keyboard to modify.
        /// </summary>
        internal static string HomeEditOtherKeyboard {
            get {
                return ResourceManager.GetString("HomeEditOtherKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify another keyboard or start from an existing keyboard to create a new one..
        /// </summary>
        internal static string HomeEditOtherKeyboardDesc {
            get {
                return ResourceManager.GetString("HomeEditOtherKeyboardDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to CiviKey&apos;s keyboard creation and modification wizard.
        ///You can choose between the four following actions to chose the keyboard you want to modify..
        /// </summary>
        internal static string HomeStepDescription {
            get {
                return ResourceManager.GetString("HomeStepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard creation and modification.
        /// </summary>
        internal static string HomeStepTitle {
            get {
                return ResourceManager.GetString("HomeStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To delete a keybaord, select the keyboard you want removed, then press &quot;Next&quot;..
        /// </summary>
        internal static string KeyboardDeletionListStepDesc {
            get {
                return ResourceManager.GetString("KeyboardDeletionListStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard deletion.
        /// </summary>
        internal static string KeyboardDeletionListStepTitle {
            get {
                return ResourceManager.GetString("KeyboardDeletionListStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Through this page you can add, delete or modify any key of the keyboard.
        ///Modifications will be saved during the next step..
        /// </summary>
        internal static string KeyboardEditionStepDesc {
            get {
                return ResourceManager.GetString("KeyboardEditionStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard modification : {0}.
        /// </summary>
        internal static string KeyboardEditionStepTitle {
            get {
                return ResourceManager.GetString("KeyboardEditionStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose among the existing keyboard the one that you want to modify, or from which you want to start to create a new keyboard..
        /// </summary>
        internal static string KeyboardListStepDesc {
            get {
                return ResourceManager.GetString("KeyboardListStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Existing keyboards list.
        /// </summary>
        internal static string KeyboardListStepTitle {
            get {
                return ResourceManager.GetString("KeyboardListStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Going back is going to erase the modifications made until now.
        ///Are you sure you want to go back ?.
        /// </summary>
        internal static string KeyboardProfileBackPopInDesc {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No, stay on this page.
        /// </summary>
        internal static string KeyboardProfileBackPopInNo {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel modifications.
        /// </summary>
        internal static string KeyboardProfileBackPopInTitle {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes, revert modifications.
        /// </summary>
        internal static string KeyboardProfileBackPopInYes {
            get {
                return ResourceManager.GetString("KeyboardProfileBackPopInYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This page enables you to modify the name of the keyboard..
        /// </summary>
        internal static string KeyboardProfileDesc {
            get {
                return ResourceManager.GetString("KeyboardProfileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard&apos;s name edition.
        /// </summary>
        internal static string KeyboardProfileTitle {
            get {
                return ResourceManager.GetString("KeyboardProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can either select an existing keyboard ot erase it, or type a new keyboard name to save your modifications under a new keyboard.
        ///If you have started your modifications with an existing keyboard, its former state will be re-established..
        /// </summary>
        internal static string SaveAsStepDesc {
            get {
                return ResourceManager.GetString("SaveAsStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to save your modifications on the keyboard named {0}.
        ///Are you sure that you want to erase this existing keyboard ?.
        /// </summary>
        internal static string SaveAsStepPopInDesc {
            get {
                return ResourceManager.GetString("SaveAsStepPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erase an existing keyboard.
        /// </summary>
        internal static string SaveAsStepPopInTitle {
            get {
                return ResourceManager.GetString("SaveAsStepPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as... step.
        /// </summary>
        internal static string SaveAsStepTitle {
            get {
                return ResourceManager.GetString("SaveAsStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the keys.
        /// </summary>
        internal static string SaveKeys {
            get {
                return ResourceManager.GetString("SaveKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel all modifications made on this keyboard and quit the wizard..
        /// </summary>
        internal static string SavingStepCancelAndQuitDesc {
            get {
                return ResourceManager.GetString("SavingStepCancelAndQuitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel and quit.
        /// </summary>
        internal static string SavingStepCancelAndQuitTitle {
            get {
                return ResourceManager.GetString("SavingStepCancelAndQuitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel all modifications made on this keyboard and go back to the beginning of the wizard..
        /// </summary>
        internal static string SavingStepCancelAndRestartDesc {
            get {
                return ResourceManager.GetString("SavingStepCancelAndRestartDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel and restart.
        /// </summary>
        internal static string SavingStepCancelAndRestartTitle {
            get {
                return ResourceManager.GetString("SavingStepCancelAndRestartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can now choose where you want to save the modifications you just made; on the &quot;{0}&quot; keyboard, or on another one..
        /// </summary>
        internal static string SavingStepDesc {
            get {
                return ResourceManager.GetString("SavingStepDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the modifications made on a new keyboard or another existing one..
        /// </summary>
        internal static string SavingStepSaveAsDesc {
            get {
                return ResourceManager.GetString("SavingStepSaveAsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as....
        /// </summary>
        internal static string SavingStepSaveAsTitle {
            get {
                return ResourceManager.GetString("SavingStepSaveAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save the modifications made on this keyboard..
        /// </summary>
        internal static string SavingStepSaveDesc {
            get {
                return ResourceManager.GetString("SavingStepSaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string SavingStepSaveTitle {
            get {
                return ResourceManager.GetString("SavingStepSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saving step.
        /// </summary>
        internal static string SavingStepTitle {
            get {
                return ResourceManager.GetString("SavingStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start over.
        /// </summary>
        internal static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keyboard creation wizard.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are about to close the keyboard edition wizard. 
        ///
        ///Are you sure that you want to do that ? All modifications unsaved will be lost..
        /// </summary>
        internal static string WizardExitPopInDesc {
            get {
                return ResourceManager.GetString("WizardExitPopInDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exiting the wizard.
        /// </summary>
        internal static string WizardExitPopInTitle {
            get {
                return ResourceManager.GetString("WizardExitPopInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
