//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CK.StandardPlugins.ObjectExplorer.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CK.StandardPlugins.ObjectExplorer.UI.Resources.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly full name : {0}.
        /// </summary>
        public static string A_AssemblyAssemblyFullName {
            get {
                return ResourceManager.GetString("A_AssemblyAssemblyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path : {0}.
        /// </summary>
        public static string A_AssemblyPath {
            get {
                return ResourceManager.GetString("A_AssemblyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string A_AssemblyPlugins {
            get {
                return ResourceManager.GetString("A_AssemblyPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins that have been discovered in the assembly.
        /// </summary>
        public static string A_AssemblyPluginsToolTip {
            get {
                return ResourceManager.GetString("A_AssemblyPluginsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string A_AssemblyServices {
            get {
                return ResourceManager.GetString("A_AssemblyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services that have been discovered in the assembly.
        /// </summary>
        public static string A_AssemblyServicesToolTip {
            get {
                return ResourceManager.GetString("A_AssemblyServicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version : {0}.
        /// </summary>
        public static string A_AssemblyVersion {
            get {
                return ResourceManager.GetString("A_AssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate logs : .
        /// </summary>
        public static string ActivateLogs {
            get {
                return ResourceManager.GetString("ActivateLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        public static string AssembliesTreeHeader {
            get {
                return ResourceManager.GetString("AssembliesTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller.
        /// </summary>
        public static string Caller {
            get {
                return ResourceManager.GetString("Caller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesTreeHeader {
            get {
                return ResourceManager.GetString("CategoriesTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition informations.
        /// </summary>
        public static string DefinitionInformationsHeader {
            get {
                return ResourceManager.GetString("DefinitionInformationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegates.
        /// </summary>
        public static string Delegates {
            get {
                return ResourceManager.GetString("Delegates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this plugin.
        /// </summary>
        public static string DisablePluginLabel {
            get {
                return ResourceManager.GetString("DisablePluginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence bad event handling errors.
        /// </summary>
        public static string DoCatchBadEventHandling {
            get {
                return ResourceManager.GetString("DoCatchBadEventHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence errors raised when a subscriber raises an error while handling this event.
        /// </summary>
        public static string DoCatchBadEventHandlingToolTip {
            get {
                return ResourceManager.GetString("DoCatchBadEventHandlingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence event errors.
        /// </summary>
        public static string DoCatchEventWhenServiceStopped {
            get {
                return ResourceManager.GetString("DoCatchEventWhenServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silence errors raised when a stopped service fires this event.
        /// </summary>
        public static string DoCatchEventWhenServiceStoppedToolTip {
            get {
                return ResourceManager.GetString("DoCatchEventWhenServiceStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log silenced event errors.
        /// </summary>
        public static string DoLogCaughtEventWhenServiceStopped {
            get {
                return ResourceManager.GetString("DoLogCaughtEventWhenServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this plugin.
        /// </summary>
        public static string EnablePluginLabel {
            get {
                return ResourceManager.GetString("EnablePluginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log end raise.
        /// </summary>
        public static string EndRaise {
            get {
                return ResourceManager.GetString("EndRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log the moment when the event has been handled by all the subscribers.
        /// </summary>
        public static string EndRaiseToolTip {
            get {
                return ResourceManager.GetString("EndRaiseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message : .
        /// </summary>
        public static string ErrorMessageLabel {
            get {
                return ResourceManager.GetString("ErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement : .
        /// </summary>
        public static string FinalRequirement {
            get {
                return ResourceManager.GetString("FinalRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralTreeHeader {
            get {
                return ResourceManager.GetString("GeneralTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to get more information about this object.
        /// </summary>
        public static string GotoToolTip {
            get {
                return ResourceManager.GetString("GotoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementations.
        /// </summary>
        public static string ImplementationsLabel {
            get {
                return ResourceManager.GetString("ImplementationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is running.
        /// </summary>
        public static string ImplementingPluginRunningToolTip {
            get {
                return ResourceManager.GetString("ImplementingPluginRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is stopped.
        /// </summary>
        public static string ImplementingPluginStoppedToolTip {
            get {
                return ResourceManager.GetString("ImplementingPluginStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching configuration that you have initiated by clicking on the &quot;Start/Stop button&quot; of this plugin .
        /// </summary>
        public static string LiveConfigurationToolTip_1 {
            get {
                return ResourceManager.GetString("LiveConfigurationToolTip_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset by clicking the icon on the right of the value.
        /// </summary>
        public static string LiveConfigurationToolTip_2 {
            get {
                return ResourceManager.GetString("LiveConfigurationToolTip_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Activated.
        /// </summary>
        public static string LogConfigActivated {
            get {
                return ResourceManager.GetString("LogConfigActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply all modifications.
        /// </summary>
        public static string LogConfigApplyModifications {
            get {
                return ResourceManager.GetString("LogConfigApplyModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel all modifications.
        /// </summary>
        public static string LogConfigCancelAllModifications {
            get {
                return ResourceManager.GetString("LogConfigCancelAllModifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Deactivated.
        /// </summary>
        public static string LogConfigDeactivated {
            get {
                return ResourceManager.GetString("LogConfigDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string LogConfigEventsHeader {
            get {
                return ResourceManager.GetString("LogConfigEventsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log configuration informations.
        /// </summary>
        public static string LogConfigInformationsGroupBoxHeader {
            get {
                return ResourceManager.GetString("LogConfigInformationsGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not bound.
        /// </summary>
        public static string LogConfigIsBoundWarningShownText {
            get {
                return ResourceManager.GetString("LogConfigIsBoundWarningShownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Service couldn&apos;t be found in the list of available services, logging this service is therefor impossible.
        /// </summary>
        public static string LogConfigIsBoundWarningToolTip_1 {
            get {
                return ResourceManager.GetString("LogConfigIsBoundWarningToolTip_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the plugin corresponding to this service is running and try re-launching the discoverer.
        /// </summary>
        public static string LogConfigIsBoundWarningToolTip_2 {
            get {
                return ResourceManager.GetString("LogConfigIsBoundWarningToolTip_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string LogConfigMethodsHeader {
            get {
                return ResourceManager.GetString("LogConfigMethodsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of loaded services : {0}.
        /// </summary>
        public static string LogConfigNumberOfLoadedServices {
            get {
                return ResourceManager.GetString("LogConfigNumberOfLoadedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of logged services : {0}.
        /// </summary>
        public static string LogConfigNumberOfLoggedServices {
            get {
                return ResourceManager.GetString("LogConfigNumberOfLoggedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string LogConfigPropertiesHeader {
            get {
                return ResourceManager.GetString("LogConfigPropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate logs on this service : .
        /// </summary>
        public static string LogConfigServiceLogActivation {
            get {
                return ResourceManager.GetString("LogConfigServiceLogActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Service to configure : .
        /// </summary>
        public static string LogConfigServiceSelection {
            get {
                return ResourceManager.GetString("LogConfigServiceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Configuration.
        /// </summary>
        public static string LogConfigTitle {
            get {
                return ResourceManager.GetString("LogConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogConfiguration : {0}.
        /// </summary>
        public static string LogConfigurationHeaderStringFormat {
            get {
                return ResourceManager.GetString("LogConfigurationHeaderStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Output.
        /// </summary>
        public static string LogConsoleTitle {
            get {
                return ResourceManager.GetString("LogConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Errors.
        /// </summary>
        public static string LogErrors {
            get {
                return ResourceManager.GetString("LogErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs on the {0} Service are : {1}.
        /// </summary>
        public static string LogServiceConfigLogStatus {
            get {
                return ResourceManager.GetString("LogServiceConfigLogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string LogsTreeHeader {
            get {
                return ResourceManager.GetString("LogsTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit this log configuration.
        /// </summary>
        public static string ModifyServiceLogConfiguration {
            get {
                return ResourceManager.GetString("ModifyServiceLogConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must exist.
        /// </summary>
        public static string MustExist {
            get {
                return ResourceManager.GetString("MustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must exist, Must run.
        /// </summary>
        public static string MustExistAndRun {
            get {
                return ResourceManager.GetString("MustExistAndRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin requires the service to be running.
        /// </summary>
        public static string MustExistAndRunServiceRefToolTip {
            get {
                return ResourceManager.GetString("MustExistAndRunServiceRefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin requires the {0} service to be existing ( but not necessarily running ).
        /// </summary>
        public static string MustExistServiceRefToolTip {
            get {
                return ResourceManager.GetString("MustExistServiceRefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must exist, Try start.
        /// </summary>
        public static string MustExistTryStart {
            get {
                return ResourceManager.GetString("MustExistTryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin requires the {0} service to be existing and will try to launch it.
        /// </summary>
        public static string MustExistTryStartServiceRefToolTip {
            get {
                return ResourceManager.GetString("MustExistTryStartServiceRefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no implementation for this service.
        /// </summary>
        public static string NoImpl {
            get {
                return ResourceManager.GetString("NoImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old version.
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin doesn&apos;t impact the service&apos;s launching.
        /// </summary>
        public static string OptionalServiceRefToolTip {
            get {
                return ResourceManager.GetString("OptionalServiceRefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional, Try to start.
        /// </summary>
        public static string OptionalTryStart {
            get {
                return ResourceManager.GetString("OptionalTryStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin will try to start the service if it exists.
        /// </summary>
        public static string OptionalTryStartServiceRefToolTip {
            get {
                return ResourceManager.GetString("OptionalTryStartServiceRefToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies all the changes made, applies changes made on other plugins as well.
        /// </summary>
        public static string P_ApplyButtonToolTip {
            get {
                return ResourceManager.GetString("P_ApplyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposed service.
        /// </summary>
        public static string P_ImplementedServicesLabel {
            get {
                return ResourceManager.GetString("P_ImplementedServicesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service that the {0} plugin exposes (there can only be one).
        /// </summary>
        public static string P_ImplementedServicesToolTip {
            get {
                return ResourceManager.GetString("P_ImplementedServicesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories : {0}.
        /// </summary>
        public static string P_PluginCategoriesLabel {
            get {
                return ResourceManager.GetString("P_PluginCategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description : {0}.
        /// </summary>
        public static string P_PluginDescriptionLabel {
            get {
                return ResourceManager.GetString("P_PluginDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid : {0}.
        /// </summary>
        public static string P_PluginGUIDLabel {
            get {
                return ResourceManager.GetString("P_PluginGUIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference url : {0}.
        /// </summary>
        public static string P_PluginURLLabel {
            get {
                return ResourceManager.GetString("P_PluginURLLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version : {0}.
        /// </summary>
        public static string P_PluginVersionLabel {
            get {
                return ResourceManager.GetString("P_PluginVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposed service configuration.
        /// </summary>
        public static string P_ServiceConfigurationLabel {
            get {
                return ResourceManager.GetString("P_ServiceConfigurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration of the exposed service. Has an impact on this plugin&apos;s launching.
        /// </summary>
        public static string P_ServiceConfigurationToolTip {
            get {
                return ResourceManager.GetString("P_ServiceConfigurationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the plugin.
        /// </summary>
        public static string P_StartButtonLabel {
            get {
                return ResourceManager.GetString("P_StartButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the plugin.
        /// </summary>
        public static string P_StopButtonLabel {
            get {
                return ResourceManager.GetString("P_StopButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching configuration for this plugin, at System level.
        /// </summary>
        public static string P_SystemConfigurationToolTip {
            get {
                return ResourceManager.GetString("P_SystemConfigurationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching configuration for this plugin, at User level.
        /// </summary>
        public static string P_UserConfigurationToolTip {
            get {
                return ResourceManager.GetString("P_UserConfigurationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service references.
        /// </summary>
        public static string PluginServiceReferencesLabel {
            get {
                return ResourceManager.GetString("PluginServiceReferencesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the services that the {0} plugin uses.
        /// </summary>
        public static string PluginServiceReferencesToolTip {
            get {
                return ResourceManager.GetString("PluginServiceReferencesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default plugin status :.
        /// </summary>
        public static string PluginStatusLabel {
            get {
                return ResourceManager.GetString("PluginStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string PluginsTreeHeader {
            get {
                return ResourceManager.GetString("PluginsTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is running.
        /// </summary>
        public static string ReferencingPluginRunningToolTip {
            get {
                return ResourceManager.GetString("ReferencingPluginRunningToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin is stopped.
        /// </summary>
        public static string ReferencingPluginStoppedToolTip {
            get {
                return ResourceManager.GetString("ReferencingPluginStoppedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Requirement for this plugin, may have been set by any plugin, can&apos;t be modified.
        /// </summary>
        public static string RequirementToolTip {
            get {
                return ResourceManager.GetString("RequirementToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to &quot;Manual&quot;.
        /// </summary>
        public static string ResetConfig {
            get {
                return ResourceManager.GetString("ResetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to &quot;None&quot;.
        /// </summary>
        public static string ResetLiveConfig {
            get {
                return ResourceManager.GetString("ResetLiveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReturnValue.
        /// </summary>
        public static string ReturnValue {
            get {
                return ResourceManager.GetString("ReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently running implementation.
        /// </summary>
        public static string RunningImplementationLabel {
            get {
                return ResourceManager.GetString("RunningImplementationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running plugins that reference this plugin.
        /// </summary>
        public static string RunningReferencingLabel {
            get {
                return ResourceManager.GetString("RunningReferencingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins that implement this service.
        /// </summary>
        public static string S_AllImplementationsLabel {
            get {
                return ResourceManager.GetString("S_AllImplementationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the plugins that implement this service (there can only be one launched at a given time).
        /// </summary>
        public static string S_AllImplementationsToolTip {
            get {
                return ResourceManager.GetString("S_AllImplementationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins that reference this service.
        /// </summary>
        public static string S_AllReferencingLabel {
            get {
                return ResourceManager.GetString("S_AllReferencingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the plugins that use this service.
        /// </summary>
        public static string S_AllReferencingToolTip {
            get {
                return ResourceManager.GetString("S_AllReferencingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Plugins.
        /// </summary>
        public static string S_LinkedPlugins {
            get {
                return ResourceManager.GetString("S_LinkedPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyInfo : {0}.
        /// </summary>
        public static string S_ServiceAssemblyInfo {
            get {
                return ResourceManager.GetString("S_ServiceAssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name : {0}.
        /// </summary>
        public static string S_ServiceAssemblyName {
            get {
                return ResourceManager.GetString("S_ServiceAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service unavailable.
        /// </summary>
        public static string S_ServiceIsOnError {
            get {
                return ResourceManager.GetString("S_ServiceIsOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner : {0}.
        /// </summary>
        public static string S_ServiceRefOwner {
            get {
                return ResourceManager.GetString("S_ServiceRefOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property name : {0}.
        /// </summary>
        public static string S_ServiceRefPropertyName {
            get {
                return ResourceManager.GetString("S_ServiceRefPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements : {0}.
        /// </summary>
        public static string S_ServiceRefRequirements {
            get {
                return ResourceManager.GetString("S_ServiceRefRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service referenced : {0}.
        /// </summary>
        public static string S_ServiceRefServiceReferenced {
            get {
                return ResourceManager.GetString("S_ServiceRefServiceReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesTreeHeader {
            get {
                return ResourceManager.GetString("ServicesTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Assembly : {0}, {1}.
        /// </summary>
        public static string ShortInformationsDisplayAssembly {
            get {
                return ResourceManager.GetString("ShortInformationsDisplayAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location : {0}.
        /// </summary>
        public static string ShortInformationsDisplayLocation {
            get {
                return ResourceManager.GetString("ShortInformationsDisplayLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name : {0}.
        /// </summary>
        public static string ShortInformationsDisplayName {
            get {
                return ResourceManager.GetString("ShortInformationsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log start raise.
        /// </summary>
        public static string StartRaise {
            get {
                return ResourceManager.GetString("StartRaise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log the moment when the event is raised.
        /// </summary>
        public static string StartRaiseToolTip {
            get {
                return ResourceManager.GetString("StartRaiseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The low level configuration changed.
        /// </summary>
        public static string SystemDisabledTitle {
            get {
                return ResourceManager.GetString("SystemDisabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local informations.
        /// </summary>
        public static string SystemInformations {
            get {
                return ResourceManager.GetString("SystemInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart CiviKey in order for the changes to take effect.
        /// </summary>
        public static string SystemStateChangedContent {
            get {
                return ResourceManager.GetString("SystemStateChangedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Action : .
        /// </summary>
        public static string UserAction {
            get {
                return ResourceManager.GetString("UserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
